spring.application.name=Product-service
spring.data.mongodb.uri=mongodb+srv://irfanshariff0234_db_user:4ZYvT9Q2CQQg3Dt8@cluster0.5jwffid.mongodb.net/Product-service?retryWrites=true&w=majority&appName=Cluster0
server.port=8081